name: Dotnet8

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use .NET 6 SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/NovoProjetoFrutas.csproj

    - name: Build the project
      run: dotnet publish ./src/NovoProjetoFrutas.csproj -c Release -o ./dist

   
